// cliente-angular/src/app/componentes/task-list/task-list.component.ts
import { Component, OnInit } from '@angular/core';
import { Task } from './task';
import { TodoService } from './../../servicios/todo.service';

@Component({
  selector: 'app-task-list',
  templateUrl: './task-list.component.html',
  styleUrls: ['./task-list.component.css']
})
export class TaskListComponent implements OnInit {

  tareas: Task[];
  estado: boolean;
  tarea: string = '';

  constructor(private _todoService: TodoService) { }

  ngOnInit(): void {
    this.listar();
  }

  listar(){
    this._todoService.getTareas().subscribe( response => {
      this.tareas = response;
    })
  }

  agregar(){
    this._todoService.addTarea(this.tarea).subscribe( () => {
      this.listar();
      this.tarea = '';
    })
  }

}

<div class="input-group mb-2 mt-3">
  <input type="text" name="tarea" [(ngModel)]="tarea"  class="form-control"/>
  <div class="input-group-append">
    <button class="btn btn-success" [disabled]="!tarea" type="button" (click)="agregar()"><i class="fa fa-plus"></i> Agregar</button>
  </div>
</div>
<ul class="list-group">
  <app-task-item (listar)="listar()" [tarea]="item" *ngFor="let item of tareas | completados:estado"></app-task-item>
</ul>

<ul class="list-group mt-2">
  <li class="list-group-item d-flex justify-content-between align-items-center">
    <div>
      <button class="btn btn-sm btn-outline-success mr-1" (click)="estado = null">Todos <span class="badge badge-warning">{{ tareas ? tareas.length : '0' }}</span></button>
      <button class="btn btn-sm btn-outline-secondary mr-1" (click)="estado = true">Completadas <span class="badge badge-success">{{ tareas | contador:true }}</span></button>
      <button class="btn btn-sm btn-outline-secondary" (click)="estado = false">Incompletas <span class="badge badge-danger">{{ tareas | contador:false }}</span></button>
    </div>
    <div>
      Total Tareas: <span class="badge badge-warning">{{ tareas ? tareas.length : '0' }}</span>
    </div>
  </li>
</ul>

// cliente-vue/src/components/TaskList.vue
<template>
    <div>
        <div class="mb-3 inline">
            <b-input-group class="mt-3">
                <b-form-input v-model="tarea"></b-form-input>
                <b-input-group-append>
                    <b-button variant="success" @click="agregar()" :disabled="!tarea.length"><b-icon icon="plus"></b-icon> Agregar</b-button>
                </b-input-group-append>
            </b-input-group>
        </div>
        <b-list-group class="mb-3">
            <b-list-group-item v-for="item in filtrar" :key="item.id" >
                <task-item :task="item" :estado="item.estado" @listar="listar()"></task-item>
            </b-list-group-item>
        </b-list-group>
        <b-list-group>
            <b-list-group-item class="d-flex justify-content-between">
                <div>
                    <b-button size="sm" variant="outline-success" class="mr-1" @click="estado=''">Todos <b-badge variant="warning">{{ tareas.length }}</b-badge></b-button>
                    <b-button size="sm" variant="outline-dark" class="mr-1" @click="estado=true">Completadas <b-badge variant="success">{{ completadas.length }}</b-badge></b-button>
                    <b-button size="sm" variant="outline-dark" @click="estado=false">Incompletas <b-badge variant="danger">{{ incompletas.length }}</b-badge></b-button>
                </div>
                <div>
                    Total Tareas: <b-badge variant="warning">{{ tareas.length }}</b-badge>
                </div> 
            </b-list-group-item>
        </b-list-group>
    </div>
</template>
<script>
import { mapActions, mapGetters } from 'vuex';
import TaskItem from './TaskItem';
export default {
    name: 'TaskListComponent',
    data() {
        return {
            tarea: '',
            estado: ''
        }
    },
    computed: {
        ...mapGetters('mtareas', ['tareas', 'completadas', 'incompletas']),
        filtrar: function(){
            if(this.estado !== '')
                return this.tareas.filter(tarea => tarea.estado === this.estado);
            else
                return this.tareas;
        }

    },
    components: {
        TaskItem,
    },
    methods: {
        ...mapActions('mtareas', ['getTareas', 'addTarea', 'deleteTarea', 'changeStatus']),

        listar(){
            this.getTareas();
        },

        agregar(){
            this.addTarea(this.tarea).then( () => {
                this.tarea = '';
            }).catch( error => {
                console.log(error);
            })
        },
        
    },
    mounted() {
        this.listar();
    },
}
</script>
