// cliente-angular/src/app/componentes/task-item/task-item.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';
import { Task } from '../../componentes/task-list/task';
import { TodoService } from '../../servicios/todo.service';
import { NgbModalOptions, NgbModal } from '@ng-bootstrap/ng-bootstrap';


@Component({
  selector: 'app-task-item',
  templateUrl: './task-item.component.html',
  styleUrls: ['./task-item.component.css']
})
export class TaskItemComponent implements OnInit {

  @Input() tarea: Task;
  @Output() listar: EventEmitter<Task[]>;
  task: Task;

  modalOptions: NgbModalOptions;
  constructor(private _todoService: TodoService, private _modalService: NgbModal) {
    this.listar = new EventEmitter();
    this.modalOptions = {
      backdrop: 'static',
      backdropClass: 'customBackdrop',
      keyboard: false
    };
  }

  ngOnInit(): void {
  }

  cambiarEstado(idTarea: number){
    this._todoService.changeStatus(idTarea).subscribe( () => {
      this.listar.emit();
    })
  }

  getTarea(id: number){
    this._todoService.getTarea(id).subscribe( response => {
      this.task = response;
    })
  }

  eliminar(idTarea: number){
    this._todoService.deleteTarea(idTarea).subscribe( () => {
      this.listar.emit();
    })
  }

  modificar(){
    this._todoService.editTarea(this.task).subscribe( () => {
      this._modalService.dismissAll();
      this.listar.emit();
    })
  }

  fopenModal(id: number, contenido: any ){
    this.getTarea(id);
    this._modalService.open(contenido, this.modalOptions);
  }
}

<li class="list-group-item d-flex justify-content-between align-items-center">
  <div class="custom-control custom-checkbox">
    <input
      type="checkbox"
      class="custom-control-input"
      id="{{tarea.id}}"
      [checked]="tarea.estado"
      (change)="cambiarEstado(tarea.id)"
    >
    <label for="{{tarea.id}}" class="custom-control-label" [ngClass]="{ 'tachar':tarea.estado, 'desmarcar': !tarea.estado }">{{ tarea.tarea }}</label>
  </div>
  <div>
    <button type="button" class="btn btn-primary pill mr-1" (click)="fopenModal(tarea.id, editar)"><i class="fa fa-edit"></i></button>
    <button type="button" class="btn btn-danger pill" (click)="eliminar(tarea.id)"><i class="fa fa-trash"></i></button>
  </div>
</li>
<ng-template #editar let-modal>
  <div class="modal-header">
    <h4 class="modal-title">Modificar Tarea</h4>
    <button type="button" class="close" aria-label="Close" (click)="modal.dismiss()">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <form>
      <div class="form-group">
        <div  class="row mb-2">
          <div class="col-12">
            <label>Tarea</label>
            <input
              type="text"
              class="form-control"
              [(ngModel)]="task.tarea"
              name="tarea"
              required
            >
          </div>
        </div>
      </div>
    </form>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-danger" (click)="modal.dismiss()"><i class="fa fa-ban"></i> Cancelar</button>
    <button type="button" class="btn btn-success" (click)="modificar()"><i class="fa fa-check"></i> Aceptar</button>
  </div>
</ng-template>

// cliente-vue/src/components/TaskItem.vue
<template>
    <div>
        <div class="d-flex justify-content-between">
            <b-form-checkbox
                v-model="status"
                :value="true"    
                :unchecked-value="false" 
                @change="cambiarEstado(task.id)"
            >
                <p v-bind:class="{'tachar': task.estado}">{{ task.tarea }}</p>
            </b-form-checkbox>

            <div>
                <b-button pill variant="primary" size="sm" class="mr-1" @click="modalShow = !modalShow"><b-icon icon="pencil"></b-icon></b-button>
                <b-button pill variant="danger" size="sm" @click="eliminar(task.id)"><b-icon icon="trash"></b-icon></b-button>
            </div>
        </div>
        <b-modal v-model="modalShow" title="Modificar Tarea">
            <form ref="form" @submit.stop.prevent="handleSubmit">
                <b-form-group
                label="Tarea"
                >
                    <b-form-input
                        v-model="tarea"
                        required
                    ></b-form-input>
                </b-form-group>
            </form>
            <template v-slot:modal-footer>
                <b-button size="sm" variant="success" @click="editar(task.id)" :disabled="!tarea">
                    <b-icon icon="check"></b-icon> Modificar
                </b-button>
                <b-button size="sm" variant="danger" @click="modalShow = false">
                    <b-icon icon="x"></b-icon> Cancelar
                </b-button>
            </template>
        </b-modal>
    </div>
    
</template>
<script>
import { mapActions } from 'vuex';
export default {
    name: 'ItemTaskComponent',
    props: {
        task: {
            type: Object,
            required: true
        },
        estado: {
            type: Boolean,
            required: true
        }
    },
    data() {
        return {
            status: this.estado,
            modalShow: false,
            tarea: this.task.tarea,
        }
    },
    methods: {
        ...mapActions('mtareas', ['deleteTarea', 'editTarea', 'changeStatus']),

        cambiarEstado(idTarea){
            this.changeStatus(idTarea).then( () => {
                this.$emit('listar', null);
            }).catch( error => {
                console.log(error);
            })
        },

        eliminar(idTarea){
            this.deleteTarea(idTarea).then( () => {
                this.$emit('listar', null);
            }).catch( error => {
                console.log(error);
            })
        },

        editar(idTarea){
            let payload = { id: idTarea, tarea: this.tarea };
            this.editTarea(payload).then( () => {
                this.modalShow = false;
                this.$emit('listar', null);
            }).catch( error => {
                console.log(error);
            })
        }
    },
}
</script>
<style>
.tachar {
    text-decoration: line-through;
}
</style>
